forge "https://forgeapi.puppetlabs.com"

mod 'puppetlabs-apache',
  :git => "https://github.com/puppetlabs/puppetlabs-apache.git"

mod 'puppetlabs-firewall',
  :git => "https://github.com/puppetlabs/puppetlabs-firewall.git"

mod 'puppet-php',
  :git => "https://github.com/voxpupuli/puppet-php.git"
